// Aligned with app/nursery/page.tsx (同 id 取文件中后出现 = 高月龄覆盖)
export const NURSERY_COLLECTIONS: Record<string, {
  id: string; title: string; emoji: string; bg: string;
  desc: string; eps: number; tag: string;
  episodes: Array<{ id: string; title: string; duration_sec: number }>;
}> = {
  'h1': {
    id: 'h1', title: '火火兔习惯养成', emoji: '🐰',
    bg: 'linear-gradient(135deg,#fff3e0,#ff9800)',
    desc: '火火兔习惯养成儿歌精选，与儿歌页卡片标题一致。',
    eps: 35, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 35 }, (_, i) => ({
      id: 'ep-h1-' + (i + 1),
      title: '火火兔习惯养成 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'h10': {
    id: 'h10', title: '礼貌用语歌', emoji: '🙋',
    bg: 'linear-gradient(135deg,#7986cb,#5c6bc0)',
    desc: '礼貌用语歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 16, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 16 }, (_, i) => ({
      id: 'ep-h10-' + (i + 1),
      title: '礼貌用语歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'h11': {
    id: 'h11', title: '作息好习惯', emoji: '🛏️',
    bg: 'linear-gradient(135deg,#80cbc4,#26a69a)',
    desc: '作息好习惯儿歌精选，与儿歌页卡片标题一致。',
    eps: 14, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 14 }, (_, i) => ({
      id: 'ep-h11-' + (i + 1),
      title: '作息好习惯 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'h12': {
    id: 'h12', title: '爱护牙齿歌', emoji: '🪥',
    bg: 'linear-gradient(135deg,#f48fb1,#ec407a)',
    desc: '爱护牙齿歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 12, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: 'ep-h12-' + (i + 1),
      title: '爱护牙齿歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'h13': {
    id: 'h13', title: '分享与轮流', emoji: '🤲',
    bg: 'linear-gradient(135deg,#FFCC80,#FFB300)',
    desc: '分享与轮流儿歌精选，与儿歌页卡片标题一致。',
    eps: 18, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 18 }, (_, i) => ({
      id: 'ep-h13-' + (i + 1),
      title: '分享与轮流 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'h14': {
    id: 'h14', title: '情绪小怪兽', emoji: '👾',
    bg: 'linear-gradient(135deg,#5C6BC0,#3949AB)',
    desc: '情绪小怪兽儿歌精选，与儿歌页卡片标题一致。',
    eps: 16, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 16 }, (_, i) => ({
      id: 'ep-h14-' + (i + 1),
      title: '情绪小怪兽 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'h15': {
    id: 'h15', title: '守规则儿歌', emoji: '📏',
    bg: 'linear-gradient(135deg,#80CBC4,#26A69A)',
    desc: '守规则儿歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 14, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 14 }, (_, i) => ({
      id: 'ep-h15-' + (i + 1),
      title: '守规则儿歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'h16': {
    id: 'h16', title: '爱护环境歌', emoji: '🌍',
    bg: 'linear-gradient(135deg,#AED581,#7CB342)',
    desc: '爱护环境歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 12, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: 'ep-h16-' + (i + 1),
      title: '爱护环境歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'h17': {
    id: 'h17', title: '同理心儿歌', emoji: '💞',
    bg: 'linear-gradient(135deg,#FFCCBC,#FF8A65)',
    desc: '同理心儿歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 16, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 16 }, (_, i) => ({
      id: 'ep-h17-' + (i + 1),
      title: '同理心儿歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'h18': {
    id: 'h18', title: '团队合作歌', emoji: '🤝',
    bg: 'linear-gradient(135deg,#5C6BC0,#3949AB)',
    desc: '团队合作歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 14, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 14 }, (_, i) => ({
      id: 'ep-h18-' + (i + 1),
      title: '团队合作歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'h19': {
    id: 'h19', title: '安全意识歌', emoji: '🚧',
    bg: 'linear-gradient(135deg,#90A4AE,#607D8B)',
    desc: '安全意识歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 12, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: 'ep-h19-' + (i + 1),
      title: '安全意识歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'h2': {
    id: 'h2', title: '学习好习惯', emoji: '🛏️',
    bg: 'linear-gradient(135deg,#bbdefb,#1565c0)',
    desc: '学习好习惯儿歌精选，与儿歌页卡片标题一致。',
    eps: 14, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 14 }, (_, i) => ({
      id: 'ep-h2-' + (i + 1),
      title: '学习好习惯 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'h20': {
    id: 'h20', title: '礼貌小绅士', emoji: '🎩',
    bg: 'linear-gradient(135deg,#B39DDB,#7E57C2)',
    desc: '礼貌小绅士儿歌精选，与儿歌页卡片标题一致。',
    eps: 10, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 10 }, (_, i) => ({
      id: 'ep-h20-' + (i + 1),
      title: '礼貌小绅士 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'h21': {
    id: 'h21', title: '自信表达歌', emoji: '🎤',
    bg: 'linear-gradient(135deg,#FFB74D,#FB8C00)',
    desc: '自信表达歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 14, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 14 }, (_, i) => ({
      id: 'ep-h21-' + (i + 1),
      title: '自信表达歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'h22': {
    id: 'h22', title: '时间管理歌', emoji: '📅',
    bg: 'linear-gradient(135deg,#26A69A,#80CBC4)',
    desc: '时间管理歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 12, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: 'ep-h22-' + (i + 1),
      title: '时间管理歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'h23': {
    id: 'h23', title: '责任担当歌', emoji: '🧱',
    bg: 'linear-gradient(135deg,#8D6E63,#BCAAA4)',
    desc: '责任担当歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 10, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 10 }, (_, i) => ({
      id: 'ep-h23-' + (i + 1),
      title: '责任担当歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'h24': {
    id: 'h24', title: '抗挫折儿歌', emoji: '💪',
    bg: 'linear-gradient(135deg,#EC407A,#F48FB1)',
    desc: '抗挫折儿歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 10, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 10 }, (_, i) => ({
      id: 'ep-h24-' + (i + 1),
      title: '抗挫折儿歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'h3': {
    id: 'h3', title: '火火兔社交情商', emoji: '🐰',
    bg: 'linear-gradient(135deg,#c8e6c9,#2e7d32)',
    desc: '火火兔社交情商儿歌精选，与儿歌页卡片标题一致。',
    eps: 23, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 23 }, (_, i) => ({
      id: 'ep-h3-' + (i + 1),
      title: '火火兔社交情商 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'h4': {
    id: 'h4', title: '安全教育儿歌', emoji: '👶',
    bg: 'linear-gradient(135deg,#e0e0e0,#757575)',
    desc: '安全教育儿歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 10, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 10 }, (_, i) => ({
      id: 'ep-h4-' + (i + 1),
      title: '安全教育儿歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'h5': {
    id: 'h5', title: '学习好习惯', emoji: '🛏️',
    bg: 'linear-gradient(135deg,#bbdefb,#1565c0)',
    desc: '学习好习惯儿歌精选，与儿歌页卡片标题一致。',
    eps: 14, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 14 }, (_, i) => ({
      id: 'ep-h5-' + (i + 1),
      title: '学习好习惯 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'h6': {
    id: 'h6', title: '火火兔习惯养成', emoji: '🐰',
    bg: 'linear-gradient(135deg,#fff3e0,#ff9800)',
    desc: '火火兔习惯养成儿歌精选，与儿歌页卡片标题一致。',
    eps: 35, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 35 }, (_, i) => ({
      id: 'ep-h6-' + (i + 1),
      title: '火火兔习惯养成 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'h7': {
    id: 'h7', title: '安全教育儿歌', emoji: '👶',
    bg: 'linear-gradient(135deg,#e0e0e0,#757575)',
    desc: '安全教育儿歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 10, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 10 }, (_, i) => ({
      id: 'ep-h7-' + (i + 1),
      title: '安全教育儿歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'h8': {
    id: 'h8', title: '火火兔社交情商', emoji: '🐰',
    bg: 'linear-gradient(135deg,#c8e6c9,#2e7d32)',
    desc: '火火兔社交情商儿歌精选，与儿歌页卡片标题一致。',
    eps: 23, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 23 }, (_, i) => ({
      id: 'ep-h8-' + (i + 1),
      title: '火火兔社交情商 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'h9': {
    id: 'h9', title: '自己收玩具', emoji: '🧸',
    bg: 'linear-gradient(135deg,#ffcc80,#fb8c00)',
    desc: '自己收玩具儿歌精选，与儿歌页卡片标题一致。',
    eps: 18, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 18 }, (_, i) => ({
      id: 'ep-h9-' + (i + 1),
      title: '自己收玩具 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'l1': {
    id: 'l1', title: '常爸摇篮曲', emoji: '🦉',
    bg: 'linear-gradient(135deg,#1a237e,#283593)',
    desc: '常爸摇篮曲儿歌精选，与儿歌页卡片标题一致。',
    eps: 12, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: 'ep-l1-' + (i + 1),
      title: '常爸摇篮曲 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'l10': {
    id: 'l10', title: '自然环境声', emoji: '🌿',
    bg: 'linear-gradient(135deg,#33691e,#689f38)',
    desc: '自然环境声儿歌精选，与儿歌页卡片标题一致。',
    eps: 18, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 18 }, (_, i) => ({
      id: 'ep-l10-' + (i + 1),
      title: '自然环境声 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'l11': {
    id: 'l11', title: '轻柔纯音乐', emoji: '🎶',
    bg: 'linear-gradient(135deg,#004d40,#00796b)',
    desc: '轻柔纯音乐儿歌精选，与儿歌页卡片标题一致。',
    eps: 20, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 20 }, (_, i) => ({
      id: 'ep-l11-' + (i + 1),
      title: '轻柔纯音乐 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'l12': {
    id: 'l12', title: '咖啡馆白噪音', emoji: '☕',
    bg: 'linear-gradient(135deg,#3e2723,#6d4c41)',
    desc: '咖啡馆白噪音儿歌精选，与儿歌页卡片标题一致。',
    eps: 12, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: 'ep-l12-' + (i + 1),
      title: '咖啡馆白噪音 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'l13': {
    id: 'l13', title: '午后轻音乐', emoji: '🎼',
    bg: 'linear-gradient(135deg,#512DA8,#9575CD)',
    desc: '午后轻音乐儿歌精选，与儿歌页卡片标题一致。',
    eps: 14, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 14 }, (_, i) => ({
      id: 'ep-l13-' + (i + 1),
      title: '午后轻音乐 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'l14': {
    id: 'l14', title: '森林白噪音', emoji: '🌲',
    bg: 'linear-gradient(135deg,#1B5E20,#4CAF50)',
    desc: '森林白噪音儿歌精选，与儿歌页卡片标题一致。',
    eps: 18, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 18 }, (_, i) => ({
      id: 'ep-l14-' + (i + 1),
      title: '森林白噪音 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'l15': {
    id: 'l15', title: '夏日海浪声', emoji: '🌊',
    bg: 'linear-gradient(135deg,#0277BD,#4FC3F7)',
    desc: '夏日海浪声儿歌精选，与儿歌页卡片标题一致。',
    eps: 16, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 16 }, (_, i) => ({
      id: 'ep-l15-' + (i + 1),
      title: '夏日海浪声 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'l16': {
    id: 'l16', title: '雨滴敲玻璃', emoji: '🌧️',
    bg: 'linear-gradient(135deg,#37474F,#607D8B)',
    desc: '雨滴敲玻璃儿歌精选，与儿歌页卡片标题一致。',
    eps: 12, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: 'ep-l16-' + (i + 1),
      title: '雨滴敲玻璃 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'l17': {
    id: 'l17', title: '钢琴童话曲', emoji: '🎹',
    bg: 'linear-gradient(135deg,#283593,#5C6BC0)',
    desc: '钢琴童话曲儿歌精选，与儿歌页卡片标题一致。',
    eps: 18, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 18 }, (_, i) => ({
      id: 'ep-l17-' + (i + 1),
      title: '钢琴童话曲 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'l18': {
    id: 'l18', title: '星空冥想声', emoji: '🌌',
    bg: 'linear-gradient(135deg,#311B92,#673AB7)',
    desc: '星空冥想声儿歌精选，与儿歌页卡片标题一致。',
    eps: 16, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 16 }, (_, i) => ({
      id: 'ep-l18-' + (i + 1),
      title: '星空冥想声 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'l19': {
    id: 'l19', title: '河流潺潺声', emoji: '🏞️',
    bg: 'linear-gradient(135deg,#00695C,#26A69A)',
    desc: '河流潺潺声儿歌精选，与儿歌页卡片标题一致。',
    eps: 14, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 14 }, (_, i) => ({
      id: 'ep-l19-' + (i + 1),
      title: '河流潺潺声 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'l2': {
    id: 'l2', title: '莫扎特音乐', emoji: '🎻',
    bg: 'linear-gradient(135deg,#880e4f,#ad1457)',
    desc: '莫扎特音乐儿歌精选，与儿歌页卡片标题一致。',
    eps: 13, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 13 }, (_, i) => ({
      id: 'ep-l2-' + (i + 1),
      title: '莫扎特音乐 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'l20': {
    id: 'l20', title: '轻爵士白噪音', emoji: '🎷',
    bg: 'linear-gradient(135deg,#4E342E,#8D6E63)',
    desc: '轻爵士白噪音儿歌精选，与儿歌页卡片标题一致。',
    eps: 12, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: 'ep-l20-' + (i + 1),
      title: '轻爵士白噪音 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'l21': {
    id: 'l21', title: '专注学习乐', emoji: '🎧',
    bg: 'linear-gradient(135deg,#1A237E,#3949AB)',
    desc: '专注学习乐儿歌精选，与儿歌页卡片标题一致。',
    eps: 20, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 20 }, (_, i) => ({
      id: 'ep-l21-' + (i + 1),
      title: '专注学习乐 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'l22': {
    id: 'l22', title: '晨起唤醒曲', emoji: '🌅',
    bg: 'linear-gradient(135deg,#F57C00,#FFB74D)',
    desc: '晨起唤醒曲儿歌精选，与儿歌页卡片标题一致。',
    eps: 16, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 16 }, (_, i) => ({
      id: 'ep-l22-' + (i + 1),
      title: '晨起唤醒曲 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'l23': {
    id: 'l23', title: '午休放松曲', emoji: '😴',
    bg: 'linear-gradient(135deg,#455A64,#90A4AE)',
    desc: '午休放松曲儿歌精选，与儿歌页卡片标题一致。',
    eps: 14, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 14 }, (_, i) => ({
      id: 'ep-l23-' + (i + 1),
      title: '午休放松曲 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'l24': {
    id: 'l24', title: '晚安收心曲', emoji: '🌙',
    bg: 'linear-gradient(135deg,#311B92,#673AB7)',
    desc: '晚安收心曲儿歌精选，与儿歌页卡片标题一致。',
    eps: 12, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: 'ep-l24-' + (i + 1),
      title: '晚安收心曲 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'l3': {
    id: 'l3', title: '巴赫音乐', emoji: '🎶',
    bg: 'linear-gradient(135deg,#33691e,#558b2f)',
    desc: '巴赫音乐儿歌精选，与儿歌页卡片标题一致。',
    eps: 16, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 16 }, (_, i) => ({
      id: 'ep-l3-' + (i + 1),
      title: '巴赫音乐 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'l4': {
    id: 'l4', title: '摇篮曲天地', emoji: '👶',
    bg: 'linear-gradient(135deg,#263238,#37474f)',
    desc: '摇篮曲天地儿歌精选，与儿歌页卡片标题一致。',
    eps: 14, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 14 }, (_, i) => ({
      id: 'ep-l4-' + (i + 1),
      title: '摇篮曲天地 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'l5': {
    id: 'l5', title: '贝多芬音乐', emoji: '🎹',
    bg: 'linear-gradient(135deg,#4a148c,#6a1b9a)',
    desc: '贝多芬音乐儿歌精选，与儿歌页卡片标题一致。',
    eps: 10, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 10 }, (_, i) => ({
      id: 'ep-l5-' + (i + 1),
      title: '贝多芬音乐 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'l6': {
    id: 'l6', title: '舒伯特音乐', emoji: '🎼',
    bg: 'linear-gradient(135deg,#e65100,#ef6c00)',
    desc: '舒伯特音乐儿歌精选，与儿歌页卡片标题一致。',
    eps: 13, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 13 }, (_, i) => ({
      id: 'ep-l6-' + (i + 1),
      title: '舒伯特音乐 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'l7': {
    id: 'l7', title: '古典音乐欣赏', emoji: '🎵',
    bg: 'linear-gradient(135deg,#1a237e,#1565c0)',
    desc: '古典音乐欣赏儿歌精选，与儿歌页卡片标题一致。',
    eps: 22, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 22 }, (_, i) => ({
      id: 'ep-l7-' + (i + 1),
      title: '古典音乐欣赏 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'l8': {
    id: 'l8', title: '钢琴名曲特选窗', emoji: '🎹',
    bg: 'linear-gradient(135deg,#212121,#424242)',
    desc: '钢琴名曲特选窗儿歌精选，与儿歌页卡片标题一致。',
    eps: 29, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 29 }, (_, i) => ({
      id: 'ep-l8-' + (i + 1),
      title: '钢琴名曲特选窗 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'l9': {
    id: 'l9', title: '钢琴安眠曲', emoji: '🎹',
    bg: 'linear-gradient(135deg,#1a237e,#3949ab)',
    desc: '钢琴安眠曲儿歌精选，与儿歌页卡片标题一致。',
    eps: 15, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 15 }, (_, i) => ({
      id: 'ep-l9-' + (i + 1),
      title: '钢琴安眠曲 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  's1': {
    id: 's1', title: '亲子运动歌', emoji: '🦁',
    bg: 'linear-gradient(135deg,#7B2D8B,#E91E8C)',
    desc: '亲子运动歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 62, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 62 }, (_, i) => ({
      id: 'ep-s1-' + (i + 1),
      title: '亲子运动歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  's10': {
    id: 's10', title: '数数儿歌', emoji: '🔢',
    bg: 'linear-gradient(135deg,#1565C0,#42A5F5)',
    desc: '数数儿歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 24, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 24 }, (_, i) => ({
      id: 'ep-s10-' + (i + 1),
      title: '数数儿歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  's11': {
    id: 's11', title: '形状颜色歌', emoji: '🔺',
    bg: 'linear-gradient(135deg,#E91E63,#FF9800)',
    desc: '形状颜色歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 20, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 20 }, (_, i) => ({
      id: 'ep-s11-' + (i + 1),
      title: '形状颜色歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  's12': {
    id: 's12', title: '生活小常识歌', emoji: '🏡',
    bg: 'linear-gradient(135deg,#2E7D32,#81C784)',
    desc: '生活小常识歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 18, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 18 }, (_, i) => ({
      id: 'ep-s12-' + (i + 1),
      title: '生活小常识歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  's13': {
    id: 's13', title: '运动游戏儿歌', emoji: '🤾',
    bg: 'linear-gradient(135deg,#7B2D8B,#E91E8C)',
    desc: '运动游戏儿歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 30, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 30 }, (_, i) => ({
      id: 'ep-s13-' + (i + 1),
      title: '运动游戏儿歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  's14': {
    id: 's14', title: '生活技能儿歌', emoji: '🧦',
    bg: 'linear-gradient(135deg,#F9A825,#FFB74D)',
    desc: '生活技能儿歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 22, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 22 }, (_, i) => ({
      id: 'ep-s14-' + (i + 1),
      title: '生活技能儿歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  's15': {
    id: 's15', title: '数学启蒙儿歌', emoji: '➕',
    bg: 'linear-gradient(135deg,#1565C0,#42A5F5)',
    desc: '数学启蒙儿歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 20, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 20 }, (_, i) => ({
      id: 'ep-s15-' + (i + 1),
      title: '数学启蒙儿歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  's16': {
    id: 's16', title: '自然探索儿歌', emoji: '🦋',
    bg: 'linear-gradient(135deg,#2E7D32,#81C784)',
    desc: '自然探索儿歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 18, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 18 }, (_, i) => ({
      id: 'ep-s16-' + (i + 1),
      title: '自然探索儿歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  's17': {
    id: 's17', title: '故事接龙儿歌', emoji: '📚',
    bg: 'linear-gradient(135deg,#7B1FA2,#E91E63)',
    desc: '故事接龙儿歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 24, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 24 }, (_, i) => ({
      id: 'ep-s17-' + (i + 1),
      title: '故事接龙儿歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  's18': {
    id: 's18', title: '逻辑思维儿歌', emoji: '🧩',
    bg: 'linear-gradient(135deg,#1565C0,#42A5F5)',
    desc: '逻辑思维儿歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 20, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 20 }, (_, i) => ({
      id: 'ep-s18-' + (i + 1),
      title: '逻辑思维儿歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  's19': {
    id: 's19', title: '生活自理儿歌', emoji: '🪥',
    bg: 'linear-gradient(135deg,#2E7D32,#81C784)',
    desc: '生活自理儿歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 18, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 18 }, (_, i) => ({
      id: 'ep-s19-' + (i + 1),
      title: '生活自理儿歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  's2': {
    id: 's2', title: '认知学习儿歌', emoji: '🐰',
    bg: 'linear-gradient(135deg,#1565C0,#42A5F5)',
    desc: '认知学习儿歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 66, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 66 }, (_, i) => ({
      id: 'ep-s2-' + (i + 1),
      title: '认知学习儿歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  's20': {
    id: 's20', title: '科普小知识', emoji: '🔭',
    bg: 'linear-gradient(135deg,#F9A825,#FFB74D)',
    desc: '科普小知识儿歌精选，与儿歌页卡片标题一致。',
    eps: 16, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 16 }, (_, i) => ({
      id: 'ep-s20-' + (i + 1),
      title: '科普小知识 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  's21': {
    id: 's21', title: '小学衔接儿歌', emoji: '🏫',
    bg: 'linear-gradient(135deg,#1976D2,#64B5F6)',
    desc: '小学衔接儿歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 22, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 22 }, (_, i) => ({
      id: 'ep-s21-' + (i + 1),
      title: '小学衔接儿歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  's22': {
    id: 's22', title: '情境角色儿歌', emoji: '🎭',
    bg: 'linear-gradient(135deg,#8E24AA,#CE93D8)',
    desc: '情境角色儿歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 20, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 20 }, (_, i) => ({
      id: 'ep-s22-' + (i + 1),
      title: '情境角色儿歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  's23': {
    id: 's23', title: '探索世界儿歌', emoji: '🌍',
    bg: 'linear-gradient(135deg,#2E7D32,#81C784)',
    desc: '探索世界儿歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 18, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 18 }, (_, i) => ({
      id: 'ep-s23-' + (i + 1),
      title: '探索世界儿歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  's24': {
    id: 's24', title: '数学挑战儿歌', emoji: '➗',
    bg: 'linear-gradient(135deg,#C62828,#EF5350)',
    desc: '数学挑战儿歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 16, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 16 }, (_, i) => ({
      id: 'ep-s24-' + (i + 1),
      title: '数学挑战儿歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  's3': {
    id: 's3', title: '身体律动歌', emoji: '🎵',
    bg: 'linear-gradient(135deg,#E91E63,#FF9800)',
    desc: '身体律动歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 40, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 40 }, (_, i) => ({
      id: 'ep-s3-' + (i + 1),
      title: '身体律动歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  's4': {
    id: 's4', title: '习惯养成儿歌', emoji: '🌟',
    bg: 'linear-gradient(135deg,#2E7D32,#81C784)',
    desc: '习惯养成儿歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 35, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 35 }, (_, i) => ({
      id: 'ep-s4-' + (i + 1),
      title: '习惯养成儿歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  's9': {
    id: 's9', title: '亲子律动儿歌', emoji: '🦁',
    bg: 'linear-gradient(135deg,#7B2D8B,#E91E8C)',
    desc: '亲子律动儿歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 36, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 36 }, (_, i) => ({
      id: 'ep-s9-' + (i + 1),
      title: '亲子律动儿歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'y1': {
    id: 'y1', title: '火火兔儿歌', emoji: '🐰',
    bg: 'linear-gradient(135deg,#fff9c4,#f9a825)',
    desc: '火火兔儿歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 34, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 34 }, (_, i) => ({
      id: 'ep-y1-' + (i + 1),
      title: '火火兔儿歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'y10': {
    id: 'y10', title: '数字节奏歌', emoji: '🔢',
    bg: 'linear-gradient(135deg,#1e88e5,#42a5f5)',
    desc: '数字节奏歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 24, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 24 }, (_, i) => ({
      id: 'ep-y10-' + (i + 1),
      title: '数字节奏歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'y11': {
    id: 'y11', title: '情绪认知儿歌', emoji: '😊',
    bg: 'linear-gradient(135deg,#8e24aa,#ce93d8)',
    desc: '情绪认知儿歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 20, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 20 }, (_, i) => ({
      id: 'ep-y11-' + (i + 1),
      title: '情绪认知儿歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'y12': {
    id: 'y12', title: '交通安全儿歌', emoji: '🚗',
    bg: 'linear-gradient(135deg,#00695c,#26a69a)',
    desc: '交通安全儿歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 16, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 16 }, (_, i) => ({
      id: 'ep-y12-' + (i + 1),
      title: '交通安全儿歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'y13': {
    id: 'y13', title: '英文字母歌', emoji: '🔤',
    bg: 'linear-gradient(135deg,#8E24AA,#CE93D8)',
    desc: '英文字母歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 26, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 26 }, (_, i) => ({
      id: 'ep-y13-' + (i + 1),
      title: '英文字母歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'y14': {
    id: 'y14', title: '交通工具儿歌', emoji: '🚗',
    bg: 'linear-gradient(135deg,#00695C,#26A69A)',
    desc: '交通工具儿歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 20, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 20 }, (_, i) => ({
      id: 'ep-y14-' + (i + 1),
      title: '交通工具儿歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'y15': {
    id: 'y15', title: '职业认知儿歌', emoji: '👩‍🚒',
    bg: 'linear-gradient(135deg,#EF6C00,#FFB74D)',
    desc: '职业认知儿歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 18, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 18 }, (_, i) => ({
      id: 'ep-y15-' + (i + 1),
      title: '职业认知儿歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'y16': {
    id: 'y16', title: '节日习俗儿歌', emoji: '🎉',
    bg: 'linear-gradient(135deg,#C62828,#FF8A80)',
    desc: '节日习俗儿歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 16, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 16 }, (_, i) => ({
      id: 'ep-y16-' + (i + 1),
      title: '节日习俗儿歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'y17': {
    id: 'y17', title: '拼音启蒙儿歌', emoji: '🔠',
    bg: 'linear-gradient(135deg,#8E24AA,#CE93D8)',
    desc: '拼音启蒙儿歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 26, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 26 }, (_, i) => ({
      id: 'ep-y17-' + (i + 1),
      title: '拼音启蒙儿歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'y18': {
    id: 'y18', title: '时间认知儿歌', emoji: '⏰',
    bg: 'linear-gradient(135deg,#00695C,#26A69A)',
    desc: '时间认知儿歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 18, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 18 }, (_, i) => ({
      id: 'ep-y18-' + (i + 1),
      title: '时间认知儿歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'y19': {
    id: 'y19', title: '地理认知儿歌', emoji: '🗺️',
    bg: 'linear-gradient(135deg,#1976D2,#64B5F6)',
    desc: '地理认知儿歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 16, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 16 }, (_, i) => ({
      id: 'ep-y19-' + (i + 1),
      title: '地理认知儿歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'y2': {
    id: 'y2', title: '认知学习儿歌', emoji: '🦁',
    bg: 'linear-gradient(135deg,#fff9c4,#e65100)',
    desc: '认知学习儿歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 66, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 66 }, (_, i) => ({
      id: 'ep-y2-' + (i + 1),
      title: '认知学习儿歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'y20': {
    id: 'y20', title: '科学实验儿歌', emoji: '⚗️',
    bg: 'linear-gradient(135deg,#C62828,#EF5350)',
    desc: '科学实验儿歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 14, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 14 }, (_, i) => ({
      id: 'ep-y20-' + (i + 1),
      title: '科学实验儿歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'y21': {
    id: 'y21', title: '英文单词儿歌', emoji: '📘',
    bg: 'linear-gradient(135deg,#1565C0,#42A5F5)',
    desc: '英文单词儿歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 30, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 30 }, (_, i) => ({
      id: 'ep-y21-' + (i + 1),
      title: '英文单词儿歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'y22': {
    id: 'y22', title: '科学现象儿歌', emoji: '🌈',
    bg: 'linear-gradient(135deg,#43A047,#A5D6A7)',
    desc: '科学现象儿歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 18, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 18 }, (_, i) => ({
      id: 'ep-y22-' + (i + 1),
      title: '科学现象儿歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'y23': {
    id: 'y23', title: '历史故事儿歌', emoji: '🏺',
    bg: 'linear-gradient(135deg,#6D4C41,#A1887F)',
    desc: '历史故事儿歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 16, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 16 }, (_, i) => ({
      id: 'ep-y23-' + (i + 1),
      title: '历史故事儿歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'y24': {
    id: 'y24', title: '逻辑推理儿歌', emoji: '🧠',
    bg: 'linear-gradient(135deg,#5C6BC0,#3949AB)',
    desc: '逻辑推理儿歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 14, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 14 }, (_, i) => ({
      id: 'ep-y24-' + (i + 1),
      title: '逻辑推理儿歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'y3': {
    id: 'y3', title: '火火兔趣味百科', emoji: '🐰',
    bg: 'linear-gradient(135deg,#c8e6c9,#4caf50)',
    desc: '火火兔趣味百科儿歌精选，与儿歌页卡片标题一致。',
    eps: 39, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 39 }, (_, i) => ({
      id: 'ep-y3-' + (i + 1),
      title: '火火兔趣味百科 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'y4': {
    id: 'y4', title: '听出宝宝好性格', emoji: '👶',
    bg: 'linear-gradient(135deg,#f8bbd0,#e91e63)',
    desc: '听出宝宝好性格儿歌精选，与儿歌页卡片标题一致。',
    eps: 14, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 14 }, (_, i) => ({
      id: 'ep-y4-' + (i + 1),
      title: '听出宝宝好性格 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'y5': {
    id: 'y5', title: '火火兔儿歌', emoji: '🐰',
    bg: 'linear-gradient(135deg,#fff9c4,#f9a825)',
    desc: '火火兔儿歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 34, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 34 }, (_, i) => ({
      id: 'ep-y5-' + (i + 1),
      title: '火火兔儿歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'y6': {
    id: 'y6', title: '认知学习儿歌', emoji: '🦁',
    bg: 'linear-gradient(135deg,#fff9c4,#e65100)',
    desc: '认知学习儿歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 66, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 66 }, (_, i) => ({
      id: 'ep-y6-' + (i + 1),
      title: '认知学习儿歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'y7': {
    id: 'y7', title: '亲子运动歌', emoji: '🦁',
    bg: 'linear-gradient(135deg,#7B2D8B,#E91E8C)',
    desc: '亲子运动歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 62, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 62 }, (_, i) => ({
      id: 'ep-y7-' + (i + 1),
      title: '亲子运动歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'y8': {
    id: 'y8', title: '火火兔趣味百科', emoji: '🐰',
    bg: 'linear-gradient(135deg,#c8e6c9,#4caf50)',
    desc: '火火兔趣味百科儿歌精选，与儿歌页卡片标题一致。',
    eps: 39, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 39 }, (_, i) => ({
      id: 'ep-y8-' + (i + 1),
      title: '火火兔趣味百科 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
  'y9': {
    id: 'y9', title: '形状颜色儿歌', emoji: '🔺',
    bg: 'linear-gradient(135deg,#e53935,#ffb300)',
    desc: '形状颜色儿歌儿歌精选，与儿歌页卡片标题一致。',
    eps: 28, tag: '儿歌 · 美柚',
    episodes: Array.from({ length: 28 }, (_, i) => ({
      id: 'ep-y9-' + (i + 1),
      title: '形状颜色儿歌 · 第' + (i + 1) + '集',
      duration_sec: 90 + i * 12,
    })),
  },
}
